### ISSUE TITLE
App crashes on Huawei P8 (Android 5.0)

### ISSUE THREAD

**Issue by gnarea** [relaycorp/relaynet-gateway-android#246]
According to Google Play's pre-launch report:

```
FATAL EXCEPTION: Firebase-Messaging-Intent-Handle
Process: com.google.android.youtube, PID: 28617
java.lang.NoClassDefFoundError: aewt
	at aewu.b(PG:1)
	at duc.a(PG:230)
	at duc.get(PG:247)
	at aevw.b(PG:1)
	at dud.al(PG:5)
	at dud.aw(PG:4)
	at dud.bg(PG:8)
	at duc.a(PG:232)
	at duc.get(PG:247)
	at afke.a(PG:1)
	at aeri.b(PG:1)
	at dud.fv(PG:4)
	at duc.c(PG:269)
	at duc.get(PG:247)
	at amfk.a(PG:1)
	at eiu.K(PG:5)
	at dud.fV(PG:7)
	at duc.d(PG:334)
	at duc.get(PG:247)
	at com.google.android.apps.youtube.app.common.notification.FcmMessageListenerService.b(PG:1)
	at com.google.firebase.messaging.FirebaseMessagingService.g(PG:53)
	at avgp.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at usj.run(PG:2)
	at java.lang.Thread.run(Thread.java:831)
```

But I have not idea what Firebase or YouTube have anything to do with this.

See [logcat.txt](https://github.com/relaycorp/relaynet-gateway-android/files/5775347/logcat.txt).

**Comment by gnarea** [comment]
Never mind, it seems like a bug on Google's side and it isn't preventing publishing. References:

- https://github.com/firebase/quickstart-unity/issues/861
- https://stackoverflow.com/questions/64706041/fatal-exception-firebase-messaging-intent-handle-java-lang-noclassdeffounder
- https://issuetracker.google.com/issues/160907013
